name: Publish Python Package to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install twine and wheel
      run: pip install twine wheel

    - name: Ensure requirements.txt is present
      run: |
        echo "Checking if requirements.txt exists"
        ls -la  # Display the directory contents for debugging
        if [ ! -f requirements.txt ]; then
          echo "requirements.txt not found!"
          exit 1
        fi

    - name: Install dependencies from requirements.txt
      run: pip install -r requirements.txt

    - name: Build distribution package
      run: |
        version="${{ github.event.release.tag_name }}"
        echo "Building the distribution package..."
        export DXLIB_VERSION="$version"
        python setup.py sdist bdist_wheel
        unset DXLIB_VERSION

    - name: Verify distribution package
      run: twine check dist/*

    - name: Publish to PyPI
      run: |
        tag="${{ github.event.release.tag_name }}"
        if [[ "$tag" == "test" ]]; then
          echo "Uploading to the test PyPI server..."
          python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*$version*
        elif [[ "$tag" == "prod" ]]; then
          echo "Uploading to the production PyPI server..."
          python -m twine upload dist/*$version*
        else
          echo "Invalid tag specified. Available options are 'test' or 'prod'."
          exit 1
        fi
